on:
  push:
    branch:
      - 'cicdTest/*'

name: Regression buid workflow


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt


      - name: Generate Change logs
        id: changelogs
        working-directory: .github/workflows/
        run: python release_mail_generator.py ${{ secrets.GITHUB_TOKEN }}  v2.21


      - name: Setup JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: bash ./gradlew assembleProdFlavourDebug

      - name: Echo
        run: |
          echo ${{ steps.branch_name.outputs.branch }}

      - name: Upload generated .apk file
        uses: actions/upload-artifact@v2
        with:
          name: newYorlTimes
          path: app/build/outputs/apk/prodFlavour/debug/app-prodFlavour-debug.apk

      # - name: Upload generated mapping file
       # uses: actions/upload-artifact@v2
       # with:
       #   name: mapping
        #  path: app/build/outputs/mapping/prodGoogleRelease/mapping.txt


      #- name: Download generated .apk file
       # uses: actions/download-artifact@v2
       # with:
        #  name: newYorlTimes
        #  path: app/build/outputs/apk/prodGoogle/release/merchant-418-2.20.1.apk

     # - name: Download generated mapping file
     #   uses: actions/download-artifact@v2
      #  with:
       #   name: mapping
       #   path: app/build/outputs/mapping/prodGoogleRelease/mapping.txt